"""
Paragliding sites within ~4 hours of San Francisco.
Each site includes preferred wind directions and conditions.
"""

SITES = [
    {
        "name": "Fort Funston",
        "location": "San Francisco, CA",
        "lat": 37.7108,
        "lon": -122.5040,
        "drive_hours": 0.3,
        "description": "Classic coastal soaring site with reliable sea breezes.",
        "preferred_wind_dirs": ["W", "NW", "SW"],
        "preferred_wind_min_mph": 10,
        "preferred_wind_max_mph": 25,
        "altitude_ft": 200,
        "site_type": "coastal",
    },
    {
        "name": "Mussel Rock",
        "location": "Daly City, CA",
        "lat": 37.6693,
        "lon": -122.4916,
        "drive_hours": 0.4,
        "description": "Popular coastal ridge soaring, hang gliding and paragliding.",
        "preferred_wind_dirs": ["W", "NW"],
        "preferred_wind_min_mph": 10,
        "preferred_wind_max_mph": 25,
        "altitude_ft": 150,
        "site_type": "coastal",
    },
    {
        "name": "Mount Tamalpais",
        "location": "Mill Valley, CA",
        "lat": 37.9232,
        "lon": -122.5965,
        "drive_hours": 1.0,
        "description": "Panoramic coastal mountain with thermal and ridge soaring.",
        "preferred_wind_dirs": ["W", "SW", "NW"],
        "preferred_wind_min_mph": 8,
        "preferred_wind_max_mph": 20,
        "altitude_ft": 2571,
        "site_type": "mountain",
    },
    {
        "name": "Ed Levin County Park",
        "location": "Milpitas, CA",
        "lat": 37.4772,
        "lon": -121.8544,
        "drive_hours": 1.0,
        "description": "Foot-launch hang gliding and paragliding with thermals.",
        "preferred_wind_dirs": ["W", "SW"],
        "preferred_wind_min_mph": 5,
        "preferred_wind_max_mph": 18,
        "altitude_ft": 2600,
        "site_type": "thermal",
    },
    {
        "name": "Marina / CSUMB",
        "location": "Marina, CA",
        "lat": 36.6818,
        "lon": -121.7887,
        "drive_hours": 2.0,
        "description": "Dunes site on Monterey Bay, great for lighter winds.",
        "preferred_wind_dirs": ["NW", "W"],
        "preferred_wind_min_mph": 8,
        "preferred_wind_max_mph": 22,
        "altitude_ft": 60,
        "site_type": "coastal",
    },
    {
        "name": "Hollister Hills",
        "location": "Hollister, CA",
        "lat": 36.7977,
        "lon": -121.3944,
        "drive_hours": 2.0,
        "description": "Inland thermal site with consistent afternoon thermals.",
        "preferred_wind_dirs": ["W", "NW", "SW"],
        "preferred_wind_min_mph": 5,
        "preferred_wind_max_mph": 18,
        "altitude_ft": 2800,
        "site_type": "thermal",
    },
    {
        "name": "Mount Diablo",
        "location": "Concord, CA",
        "lat": 37.8816,
        "lon": -121.9142,
        "drive_hours": 1.2,
        "description": "Bay Area landmark with strong thermals on clear days.",
        "preferred_wind_dirs": ["W", "SW", "NW"],
        "preferred_wind_min_mph": 5,
        "preferred_wind_max_mph": 20,
        "altitude_ft": 3849,
        "site_type": "mountain",
    },
    {
        "name": "Slide Mountain (Cache Creek)",
        "location": "Lake County, CA",
        "lat": 39.0651,
        "lon": -122.7353,
        "drive_hours": 2.5,
        "description": "Northern California thermal site with long XC potential.",
        "preferred_wind_dirs": ["SW", "W", "NW"],
        "preferred_wind_min_mph": 5,
        "preferred_wind_max_mph": 18,
        "altitude_ft": 3200,
        "site_type": "thermal",
    },
    {
        "name": "Hat Creek / Burney",
        "location": "Shasta County, CA",
        "lat": 40.8774,
        "lon": -121.4530,
        "drive_hours": 3.5,
        "description": "Remote volcanic plateau known for epic XC thermal flights.",
        "preferred_wind_dirs": ["W", "SW"],
        "preferred_wind_min_mph": 5,
        "preferred_wind_max_mph": 18,
        "altitude_ft": 3400,
        "site_type": "thermal",
    },
    {
        "name": "Dunlap / Kings Canyon",
        "location": "Fresno County, CA",
        "lat": 36.7298,
        "lon": -119.1168,
        "drive_hours": 3.5,
        "description": "Central Valley foothills with strong summer thermals.",
        "preferred_wind_dirs": ["W", "SW", "NW"],
        "preferred_wind_min_mph": 5,
        "preferred_wind_max_mph": 20,
        "altitude_ft": 3500,
        "site_type": "thermal",
    },
    {
        "name": "Mount Vaca",
        "location": "Vacaville, CA",
        "lat": 38.4680,
        "lon": -122.0580,
        "drive_hours": 1.5,
        "description": "Highest peak in the Vaca Mountains, excellent XC thermal flying with views of the Central Valley and Bay Area.",
        "preferred_wind_dirs": ["SW", "W", "NW"],
        "preferred_wind_min_mph": 5,
        "preferred_wind_max_mph": 18,
        "altitude_ft": 2819,
        "site_type": "thermal",
    },
    {
        "name": "Potato Hill",
        "location": "Hopland, CA",
        "lat": 38.9770,
        "lon": -123.1130,
        "drive_hours": 2.0,
        "description": "Mendocino County thermal site popular for XC flights toward the coast and inland valleys.",
        "preferred_wind_dirs": ["NW", "W", "SW"],
        "preferred_wind_min_mph": 5,
        "preferred_wind_max_mph": 18,
        "altitude_ft": 2400,
        "site_type": "thermal",
    },
    {
        "name": "Blue Rock / Berryessa",
        "location": "Napa County, CA",
        "lat": 38.5990,
        "lon": -122.2530,
        "drive_hours": 1.5,
        "description": "Lake Berryessa foothills launch with SW-facing slopes and good thermal development on warm days.",
        "preferred_wind_dirs": ["SW", "W"],
        "preferred_wind_min_mph": 5,
        "preferred_wind_max_mph": 18,
        "altitude_ft": 1800,
        "site_type": "thermal",
    },
    {
        "name": "Santa Barbara Elings Park",
        "location": "Santa Barbara, CA",
        "lat": 34.4025,
        "lon": -119.7274,
        "drive_hours": 4.0,
        "description": "Classic coastal bluff site with reliable thermal and soaring.",
        "preferred_wind_dirs": ["W", "SW"],
        "preferred_wind_min_mph": 8,
        "preferred_wind_max_mph": 22,
        "altitude_ft": 400,
        "site_type": "coastal",
    },
]
